name: Build and Publish Docker image on GitHub Container Registry

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
    paths-ignore:
      - '*.md'
      - LICENSE
      - 'example.flaskenv'
      - '.gitattributes'
      - '.github/workflows/docker.yml'
      - '.dockerignore'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/laserspew/meal-server:latest
            ghcr.io/laserspew/meal-server:${{ github.ref_name }}
          push: true

      - name: Show image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
